// GENERATED by presentation-sanity — DO NOT EDIT.
//
// Wires the shared Vue components into VitePress so the same components back
// both the Slidev deck and the blog:
//
//   * every component file is registered globally under its filename, which
//     is exactly the convention Slidev already uses. `<DataValue>`,
//     `<ManimFigure>`, `<FigureImage>` therefore work in markdown with no
//     per-file imports.
//   * `ProvenancePanel` is mounted once in the `layout-bottom` slot — the
//     VitePress equivalent of Slidev's `global-bottom.vue` singleton.
import { h } from 'vue'
import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'
__THEME_IMPORTS__

// Literal globs (Vite requires static patterns), in priority order: a later
// directory overrides an earlier one, so a presentation's own component wins
// over the shared component of the same name.
const sources = [
__COMPONENT_GLOBS__
]

const components: Record<string, any> = {}
for (const modules of sources) {
  for (const [path, mod] of Object.entries(modules)) {
    const name = path.split('/').pop()!.replace(/\.vue$/, '')
    if (mod?.default) components[name] = mod.default
  }
}

export default {
  extends: DefaultTheme,
  Layout() {
    const panel = components.ProvenancePanel
    return h(DefaultTheme.Layout, null, panel ? { 'layout-bottom': () => h(panel) } : {})
  },
  enhanceApp({ app }) {
    for (const [name, component] of Object.entries(components)) {
      app.component(name, component)
    }
  },
} satisfies Theme
