// GENERATED by presentation-sanity — DO NOT EDIT.
//
// Wires the subject's shared Vue components into VitePress so the same
// `components/` directory backs both the Slidev deck and the blog:
//
//   * every `components/*.vue` is registered globally under its filename,
//     which is exactly the convention Slidev already uses. `<DataValue>`,
//     `<ManimFigure>`, `<FigureImage>` therefore work in markdown with no
//     per-file imports.
//   * `ProvenancePanel` is mounted once in the `layout-bottom` slot — the
//     VitePress equivalent of Slidev's `global-bottom.vue` singleton.
import { h } from 'vue'
import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'
__THEME_IMPORTS__

// Literal glob (Vite requires a static pattern); this file always sits at
// `<root>/.vitepress/theme/index.ts`, so `../../components` is the shared dir.
const shared = import.meta.glob<Record<string, any>>('../../components/*.vue', {
  eager: true,
})

export default {
  extends: DefaultTheme,
__LAYOUT__
  enhanceApp({ app }) {
    for (const [path, mod] of Object.entries(shared)) {
      const name = path.split('/').pop()!.replace(/\.vue$/, '')
      if (mod?.default) app.component(name, mod.default)
    }
  },
} satisfies Theme
